export { YourHobbies } from './your-hobbies'
export { Welcome } from './welcome'
export { PersonalInfo } from './personal-info'
export { EditPhoto } from './edit-photo'
export { WorkExperience } from './work-experience'
export { Success } from './success'